services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/docker/certs:/etc/nginx/certs
    environment:
      TRUST_DOWNSTREAM_PROXY: false

networks:
  proxy:
    name: nginx-proxy
    external: true
