
services:
  mihomo:
    container_name: mihomo
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    networks:
      - proxy
    volumes:
      - /srv/docker/mihomo:/root/.config/mihomo/
    ports:
      - "7890:7890"
      - "9090:9090"

networks:
  proxy:
    name: nginx-proxy
    external: true

